branches = [
    'run'               ,
    'lumi'              ,
    'event'             ,
    'npv'               ,

    'mass'              ,
    'mcorr'             ,
    'pt'                ,
    'eta'               ,
    'phi'               ,
    'charge'            ,

    'dr'                ,

    'mass'          ,

    'pv_x'              ,
    'pv_y'              ,
    'pv_z'              ,

    'bs_x0'             ,
    'bs_y0'             ,
    'bs_z0'             ,

    'bs_x'              ,
    'bs_y'              ,

    'vx'                ,
    'vy'                ,
    'vz'                ,
    'vtx_chi2'          ,
    'vtx_prob'          ,

    'cos2d'             ,
    'lxy'               ,
    'lxy_err'           ,
    'lxy_sig'           ,

    'mu_pt'            ,
    'mu_eta'           ,
    'mu_phi'           ,
    'mu_e'             ,
    'mu_mass'          ,
    'mu_charge'        ,
    'mu_id_loose'      ,
    'mu_id_soft'       ,
    'mu_id_medium'     ,
    'mu_id_tight'      ,
    'mu_id_soft_mva'   ,
    'mu_dxy'           ,
    'mu_dxy_e'         ,
    'mu_dxy_sig'       ,
    'mu_dz'            ,
    'mu_dz_e'          ,
    'mu_dz_sig'        ,
    'mu_bs_dxy'        ,
    'mu_bs_dxy_e'      ,
    'mu_bs_dxy_sig'    ,
    'mu_cov_pos_def'   ,

    'ele_pt'            ,
    'ele_eta'           ,
    'ele_phi'           ,
    'ele_e'             ,
    'ele_mass'          ,
    'ele_charge'        ,
    'ele_id_iso_wpLoose',
    'ele_id_iso_wp90'   ,
    'ele_id_iso_wp80'   ,
    'ele_id_noIso_wpLoose',
    'ele_id_noIso_wp90'   ,
    'ele_id_noIso_wp80'   ,
    'ele_dxy'           ,
    'ele_dxy_e'         ,
    'ele_dxy_sig'       ,
    'ele_dz'            ,
    'ele_dz_e'          ,
    'ele_dz_sig'        ,
    'ele_bs_dxy'        ,
    'ele_bs_dxy_e'      ,
    'ele_bs_dxy_sig'    ,
    'ele_cov_pos_def'   ,
]

paths = [
    'HLT_Mu7_IP4'     ,
    'HLT_Mu8_IP3'     ,
    'HLT_Mu8_IP5'     ,
    'HLT_Mu8_IP6'     ,
    'HLT_Mu8p5_IP3p5' ,
    'HLT_Mu9_IP4'     ,
    'HLT_Mu9_IP5'     ,
    'HLT_Mu9_IP6'     ,
    'HLT_Mu10p5_IP3p5',
    'HLT_Mu12_IP6'    ,
]

branches += paths
branches += [path+'_ps' for path in paths]
